### ISSUE TITLE
Cant merge an json Array

### ISSUE THREAD

**Issue by CoHyper** [joshswan/gulp-merge-json#11]
- Actual behaviour
  `{"modules": [{"id": 2}]}`
- Expected behaviour
  `{"modules": [{"id": 1}, {"id": 2}]}`
- Reproduce
  file1.json
  `{"modules": [{"id": 1}]}`
  file2.json
  `{"modules": [{"id": 2}]}`

```
var
    gulp = require('gulp'),
    jsonMinify = require('gulp-jsonminify'),
    mergeJSON = require('gulp-merge-json'),
    rename = require('gulp-rename');

return gulp.src('config/**/*.json')
    .pipe(merge('manni.json'))
    .pipe(gulp.dest(this.opts.DIR_BUILD_DIST));

/*
        .pipe(jsonMinify())
        .pipe(rename('manni.min.json'))
        .pipe(gulp.dest(this.opts.DIR_BUILD_DIST))
        .pipe(gulp.dest(this.opts.DIR_BUILD_APP_WWW));
*/
```

**Comment by joshswan** [comment]
Unfortunately this is currently expected behavior when the array contains objects. The actual object merging is handled by [deepmerge](https://github.com/KyleAMathews/deepmerge), which concats simple array values but merges objects. There are a couple of open PRs (e.g. https://github.com/KyleAMathews/deepmerge/pull/21) that seem like they'll solve this issue, but there hasn't been much movement lately. Once they're merged or an alternative is found, I'd be happy to accept a PR to expose a setting for this behavior.

**Comment by CoHyper** [comment]
my solution
- [gulp-grunt](https://www.npmjs.com/package/gulp-grunt)
- [grunt-merge-json](https://www.npmjs.com/package/grunt-merge-json)

**Comment by joshswan** [comment]
I didn't think of using lodash's merge. Version 0.4.0 that was just published to npm has a "concatArrays" option that should do what you're looking for now. I will update the documentation soon, but if you were to replace `merge('manni.json')` with `merge('manni.json', false, false, false, false, true)` or `merge({ filename: 'manni.json', concatArrays: true })`, you should get the desired result.
