### ISSUE TITLE
filename

### ISSUE THREAD

**Issue by dotherightthing** [joshswan/gulp-merge-json#15]
Hi,

I've added `merge-json` to my build and the JSON merging is working fine.

However the destination directory seems to be overridden by `fileName`

```
gulp.task('merge_json', function() {

  // merge the data files
  return gulp.src('contents/pages/**/*.json')
              // merge json files into a single tests file for handlebars
              .pipe(merge({
                fileName: 'tests.json',
                concatArrays: true
              }))
              .pipe(gulp.dest('./contents/pages_temp/'));
              // desired output: /contents/pages_temp/folder1/folder2/tests.json
              //  actual output: /contents/pages_temp/tests.json
});

```

If I disable `merge-json` it works as expected:

```
gulp.task('merge_json', function() {

  // merge the data files
  return gulp.src('contents/pages/**/*.json')
              // merge json files into a single tests file for handlebars
              //.pipe(merge({
              //  fileName: 'tests.json',
              //  concatArrays: true
              //}))
              .pipe(gulp.dest('./contents/pages_temp/'));
              // desired output: /contents/pages_temp/folder1/folder2/test1.json
              //  actual output: /contents/pages_temp/folder1/folder2/test1.json
});
```

Is this a bug or is there an option I can toggle on to make this work?

Thanks,
Dan

**Comment by joshswan** [comment]
You can't use a globstar pattern and produce separate outputs per directory. When using `gulp.src` with that pattern, ALL the matching files, regardless of how deep in the file structure, are included in the stream and it would be impossible to separate out files in different subdirectories on the fly.

The solution to your problem is to break it up so that your `gulp.src` encompasses only the files you want to merge:

``` javascript
const combine = require('merge-stream'); // Note dependency
const path = require('path');

const directories = [
  'folder1/folder2',
];

gulp.task('merge_json', function() {
  // Perform merge per-directory
  const tasks = directories.map((directory) => {
    return gulp.src(path.join('contents/pages', directory, '**/*.js'))
      .pipe(merge({
        fileName: 'test.json',
        concatArrays: true,
      })
      .pipe(gulp.dest(path.join('contents/pages_temp', directory))
  }); 

  return combine(tasks);
});

```

**Comment by dotherightthing** [comment]
Ah, ok, thanks for the clarification, I'm new to Gulp.

My problem is that I don't know what 'folder1' and 'folder2' are. I'm basically building up a UI library of sorts and want to be able to add and rename folders without updating the gulpfile. There will be a folder per component/module.

I have several other plugins that do this, is there something different about a file merge that makes this impossible?

``` javascript
var gulp = require('gulp');
var rename = require('gulp-rename');
var markdownToJSON = require('gulp-markdown-to-json');

// markdown to JSON
gulp.task('markdownToJSON', function(){
  // get the README file from each component folder
  return gulp.src('./contents/pages/**/README.md')
    // convert it into JSON
    .pipe(markdownToJSON(marked))
    // add an underscore to the file name
    .pipe(rename({
      prefix: "_"
    }))
    // output it to the source component folder
    .pipe(gulp.dest('./contents/pages'))
    // expected output: contents/pages/folder1/folder2/_README.json
    //   actual output: contents/pages/folder1/folder2/_README.json
});
```

**Comment by joshswan** [comment]
Yeah it's conceptually a bit different. In the example above, it's finding all README.md files, processing them _individually_, and then putting them in their corresponding place in the destination folder. Since each file is independent and there's a 1:1 input to output, it's pretty simple and that's the expected result. On the other hand, when merging/combining files, it's generally the default behavior to just combine everything that's passed via `gulp.src` as that's the most flexible option. If you pass everything, it combines everything; if you pass a directory (or array of directories), it combines everything in that directory. Thus, you eliminate the complexity of walking down the file tree and combining at each level from a library that should only be concerned with the actual combining.

In the gulp docs, they have a [recipe](https://github.com/gulpjs/gulp/blob/master/docs/recipes/running-task-steps-per-folder.md) for per-directory tasks with unknown directories (using `fs` to find directories), so you can take a look at that to modify the original example I did. However, this method is going to depend on a consistent folder structure, despite being unknown (e.g. always two levels down - a/b/test.json).

You can also look into this [gulp plugin](https://www.npmjs.com/package/gulp-recursive-folder), which seems to do the recursive walking and allow you to then pass the results to `gulp.src`, thus allowing you to perform the combining in just one part of the folder structure. (I've never used the plugin so I can't guarantee it'll work but the docs looked promising.)

**Comment by dotherightthing** [comment]
Many thanks, I used the first option as it was easier to get my head around. Thanks for all your help :)
