### ISSUE TITLE
Possible to keep folder structure/original file name?

### ISSUE THREAD

**Issue by ryanhagerty** [joshswan/gulp-merge-json#17]
Let's say I multiple folders that I need to go through, and in each of those folders I'll have two JSON files with unique names, such as: `Link.config.json` and `Link.css.json`. 

Is it possible to combine `Link.css.json` _into_ `Link.config.json` for multiple folders?

Manually works great:

```
gulp.task('merge', function () {
  var options = [];
  return gulp.src('./src/components/**/*.json')
    .pipe(merge({
        fileName: 'Link.config.json'
    }))
    .pipe(gulp.dest('./src/components/01-Units/Links/Link/'));
});
```

But I need to remove to the specific `fileName` to be something like `:name.config.json` and the `dest` to be the same as the `src`.

So it would look something like:

```
gulp.task('merge', function () {
  var options = [];
  return gulp.src('./src/components/**/*.json')
    .pipe(merge({
        fileName: :name + '.config.json'
    }))
    .pipe(gulp.dest('./src/components/**/'));
});
```

**Comment by joshswan** [comment]
Take a look at my answer to a similar question in a previous issue: https://github.com/joshswan/gulp-merge-json/issues/15#issuecomment-253284266. Basically, using the pattern you have currently will merge every JSON file in `src/components` into ONE file, which doesn't sound like what you want. Using `path` to map out the directories and then performing the merge for each individually would allow you to get the result you're looking for since you'll only merge the files in that directory and you'll have the name available for the custom output name.
